services:
  appointment-service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles/
      - media_volume:/app/media/
  nginx:
    container_name: nginx-web
    image: nginx:alpine
    depends_on:
      - appointment-service
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./certbot/www/:/var/www/certbot/:ro
      - static_volume:/app/staticfiles/
      - media_volume:/app/media/
      - /etc/letsencrypt/live/luckypilka.ru/fullchain.pem:/etc/letsencrypt/live/luckypilka.ru/fullchain.pem
      - /etc/letsencrypt/live/luckypilka.ru/privkey.pem:/etc/letsencrypt/live/luckypilka.ru/privkey.pem
  postgres:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  static_volume:
  media_volume:
  pgdata:
