# Generated by Django 5.1.1 on 2024-10-24 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='appointment_buffer_time',
            field=models.FloatField(blank=True, help_text='Время между текущим моментом и первым доступным интервалом на текущий день (не влияет на завтра)', null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='finish_time',
            field=models.TimeField(blank=True, help_text='Время конца рабочего дня', null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='lead_time',
            field=models.TimeField(blank=True, help_text='Время начала рабочего дня', null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='slot_duration',
            field=models.PositiveIntegerField(blank=True, help_text='(Количество слотов доступных для записи к данному работнику, день будет разбит на промежутки по установленному количеству минут)', null=True),
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.staffmember')),
            ],
        ),
    ]
