# Generated by Django 5.1.1 on 2025-03-14 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_remove_calendarsettings_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='staff_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.staffmember'),
        ),
    ]
