# Generated by Django 5.1.1 on 2025-03-14 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_alter_appointmentrequest_staff_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedappointmentrequest',
            name='staff_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.staffmember'),
        ),
    ]
