# Generated by Django 5.1.1 on 2025-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedappointment',
            name='not_come',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='appointment_buffer_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='finish_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='lead_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='slot_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
