# Generated by Django 5.1.1 on 2025-03-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainController', '0002_remove_meet_time_slot_review_delete_chank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carousel/')),
            ],
        ),
    ]
