# Generated by Django 5.1.1 on 2025-03-21 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0003_remove_customuser_birthday_customuser_year_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
