# Generated by Django 5.1.1 on 2025-05-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainUser', '0007_customuser_confirmed_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_link_tg',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
